//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabHairTrigger
        {
            get
            {
                return SteamVR_Actions.default_GrabHairTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.default_TouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuPress
        {
            get
            {
                return SteamVR_Actions.default_MenuPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadRight
        {
            get
            {
                return SteamVR_Actions.default_TouchpadRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadLeft
        {
            get
            {
                return SteamVR_Actions.default_TouchpadLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripLong
        {
            get
            {
                return SteamVR_Actions.default_GripLong;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
